CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_BT_SETTINGS=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y
CONFIG_HWINFO=y

CONFIG_BT=y
CONFIG_BT_L2CAP_TX_BUF_COUNT=5
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_OBSERVER=y
CONFIG_BT_BROADCASTER=y

CONFIG_BT_CTLR_DUP_FILTER_LEN=0
CONFIG_BT_CTLR_LE_ENC=n
CONFIG_BT_CTLR_LE_PING=n
CONFIG_BT_DATA_LEN_UPDATE=n
CONFIG_BT_PHY_UPDATE=n
CONFIG_BT_CTLR_MIN_USED_CHAN=n
CONFIG_BT_CTLR_PRIVACY=n
CONFIG_BT_CTLR_CHAN_SEL_2=n

CONFIG_BT_MESH=y
CONFIG_BT_MESH_MODEL_EXTENSIONS=y
CONFIG_BT_MESH_RELAY=y
CONFIG_BT_MESH_FRIEND=n
CONFIG_BT_MESH_PB_GATT=y
CONFIG_BT_MESH_PB_ADV=y
CONFIG_BT_MESH_GATT_PROXY=y

CONFIG_BT_MESH_SUBNET_COUNT=2
CONFIG_BT_MESH_APP_KEY_COUNT=2
CONFIG_BT_MESH_MODEL_GROUP_COUNT=2
CONFIG_BT_MESH_LABEL_COUNT=3


#RTL_DEBUG[🔧] common mesh conf
#2025-07-30
CONFIG_DEBUG_OPTIMIZATIONS=n

CONFIG_LOG=y

CONFIG_SHELL=y
CONFIG_BT_MESH_SHELL=y
# CONFIG_SHELL_HISTORY=n
CONFIG_SHELL_CMDS_SELECT=n
CONFIG_SHELL_HELP=n
CONFIG_SHELL_TAB_AUTOCOMPLETION=n
CONFIG_SHELL_CMD_BUFF_SIZE=32
CONFIG_FLASH_SHELL=n
#配置为1500 发现执行mesh reset-local会出现shell uart线程的栈溢出
CONFIG_SHELL_STACK_SIZE=2048

CONFIG_LOG_BUFFER_SIZE=1024


CONFIG_BT_MESH_CDB=y

CONFIG_BT_MESH_CRPL=30
CONFIG_BT_MESH_MSG_CACHE_SIZE=30

CONFIG_NVS_LOOKUP_CACHE=y
CONFIG_SETTINGS_NVS_NAME_CACHE=y
CONFIG_SETTINGS_NVS_NAME_CACHE_SIZE=32

#长时间运行mesh 使用率有720byte
CONFIG_MAIN_STACK_SIZE=1200

CONFIG_SPEED_OPTIMIZATIONS=y


# CONFIG_STDOUT_CONSOLE=y
# enable to use thread names
CONFIG_SEGGER_SYSTEMVIEW=n
CONFIG_THREAD_NAME=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_TRACING=y
CONFIG_TRACING_BACKEND_RAM=y
# enable for post-mortem tracing
CONFIG_SEGGER_SYSVIEW_POST_MORTEM_MODE=n
CONFIG_TRACING_BUFFER_SIZE=4096

CONFIG_TICKLESS_KERNEL=n
CONFIG_TIMESLICE_SIZE=10

CONFIG_BT_MESH_UNPROV_BEACON_INT=10

#使用pubic addr
CONFIG_BT_PRIVACY=n

CONFIG_DEBUG_COREDUMP=y
CONFIG_DEBUG_COREDUMP_BACKEND_LOGGING=y

