#ifdef __cplusplus
extern "C" {
#endif

/** @brief  OTA Write callback data type definition. */
#define OTA_WRITE_CHAR_VAL  0x01
#define OTA_VALUE_ENTER     0x01

/** @brief  Demo Profile service related UUIDs. */
#define GATT_UUID_CHAR_OTA                          0xFFD1
#define GATT_UUID_CHAR_MAC                          0xFFD2
#define GATT_UUID_CHAR_PATCH_VERSION                0xFFD3
#define GATT_UUID_CHAR_APP_VERSION                  0xFFD4
#define GATT_UUID_CHAR_IMAGE_VERSION_FIRST          0xFFE0
#define GATT_UUID_CHAR_IMAGE_VERSION_SECOND         0xFFE1
#define GATT_UUID_CHAR_DEVICE_INFO                  0xFFF1
#define GATT_UUID_CHAR_PROTOCOL_INFO                0xFFF3
#define GATT_UUID_CHAR_SECTION_SIZE_FIRST           0xFFF4
#define GATT_UUID_CHAR_SECTION_SIZE_SECOND          0xFFF5


#define BT_UUID_CHAR_OTA \
	BT_UUID_DECLARE_16(GATT_UUID_CHAR_OTA)

#define BT_UUID_CHAR_MAC \
	BT_UUID_DECLARE_16(GATT_UUID_CHAR_MAC)

#define BT_UUID_CHAR_PATCH_VERSION \
	BT_UUID_DECLARE_16(GATT_UUID_CHAR_PATCH_VERSION)

#define BT_UUID_CHAR_APP_VERSION \
	BT_UUID_DECLARE_16(GATT_UUID_CHAR_APP_VERSION)

#define BT_UUID_CHAR_DEVICE_INFO \
	BT_UUID_DECLARE_16(GATT_UUID_CHAR_DEVICE_INFO)

#define BT_UUID_CHAR_IMAGE_VERSION_FIRST \
	BT_UUID_DECLARE_16(GATT_UUID_CHAR_IMAGE_VERSION_FIRST)

#define BT_UUID_CHAR_IMAGE_VERSION_SECOND \
	BT_UUID_DECLARE_16(GATT_UUID_CHAR_IMAGE_VERSION_SECOND)

#define BT_UUID_CHAR_PROTOCOL_INFO \
	BT_UUID_DECLARE_16(GATT_UUID_CHAR_PROTOCOL_INFO)

#define BT_UUID_CHAR_SECTION_SIZE_FIRST \
	BT_UUID_DECLARE_16(GATT_UUID_CHAR_SECTION_SIZE_FIRST)

#define BT_UUID_CHAR_SECTION_SIZE_SECOND \
	BT_UUID_DECLARE_16(GATT_UUID_CHAR_SECTION_SIZE_SECOND)


#ifdef __cplusplus
}
#endif
